framework:
    secret: test
    test: ~
    session:
        storage_id: session.storage.filesystem
    form:            true
    csrf_protection: true
    validation:       
        enabled: true
        enable_annotations: true
    router:
        resource: routing.yml